### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by molelightn** [DeerMaximum/Technische-Alternative-CMI#43]
Hi there DeerMaximum, 

first of all thanks for putting effort into this project. I was looking for long time for CMI to HA integration.
I have 9 CAN devices running on Node40 is the EZ3. With Version 1.4.1 of your integration i get following error during setup:

**Error while communicating with a device (40): Failure during the CAN-request/parameter not available for this device**

Setup never finish, i kept it running for 20min as you wrote per device it will take +1min.

Any idea? Do you need debug logs? 

Thank you for your help.
br mole

**Comment by DeerMaximum** [comment]
Could you set the integration to the debug log level and send me the logs?

```yaml
logger:
  default: info
  logs:
    custom_components.ta_cmi: debug
    ta_cmi: debug
```
