### ISSUE TITLE
Adjusting entity

### ISSUE THREAD

**Issue by Lens40** [DeerMaximum/Technische-Alternative-CMI#58]
Hi there,

thanks for the great integration ! I am trying to figure out how I can adjust one of the entity setting so it is displayed in the energy dashboard.

On **sensor.node_1_analog_logging_22** of my UVR16x2 I have the total kWh output of my solar warm water production. So  basically I can retrieve the data just fine. To be able to integrate the data I need to change the state_class from measurement to total_increasing. By doing this in the developer tools it stops updating the data and from time to time the settings are reset. Not sure why. Do you have an idea how to approach this?

Thanks for your help :)

**Comment by DeerMaximum** [comment]
With the latest version (1.8.1), you only need to change the state_class in configuration.yaml.

```yaml
homeassistant:
  customize_glob: 
    "sensor.node_1_analog_logging_22":
        state_class: total_increasing
```
