### ISSUE TITLE
Issue adding second CMI to the integration

### ISSUE THREAD

**Issue by dottorer** [DeerMaximum/Technische-Alternative-CMI#99]
I operate 2 CMIs in two location. The 2 networks are LAN-LAN connected with wireguard and both CMIs have distinct fixed IPs. I can access the second remote CMI in a browser using the base URL, but cannot add it as a second device to the integration. 

Is this in principle supported? It might be a time-out issue due to the remote latency to retrieve the entities for the channels.

BTW: Thank a million for building the CMI integration - this is great!

**Comment by DeerMaximum** [comment]
I haven't considered this use case yet. But from my understanding this should be already possible. 
Can you send me the debug logs when you try to connect your second device?

```yaml
logger:
  default: info
  logs:
    custom_components.ta_cmi: debug
    ta_cmi: debug
```
